"""Usage statistics models for chat sessions."""

from pydantic import BaseModel, Field, computed_field


class TokenUsageStats(BaseModel):
    """Token usage statistics accumulated across all LLM calls.

    Attributes:
        prompt_tokens: Total input tokens sent to the LLM.
        completion_tokens: Total output tokens generated by the LLM.
        total_tokens: Sum of prompt and completion tokens (computed).
    """

    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_tokens(self) -> int:
        """Total tokens (prompt + completion)."""
        return self.prompt_tokens + self.completion_tokens


class ToolCallStats(BaseModel):
    """Statistics about tool calls during a chat session.

    Attributes:
        by_tool: Counts of calls keyed by tool name.
        by_server: Counts of calls keyed by server name.
            Synthetic tools are tracked under the ``"_synthetic"`` server.
        total: Total number of tool calls made (computed).
    """

    by_tool: dict[str, int] = Field(default_factory=dict)
    by_server: dict[str, int] = Field(default_factory=dict)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total(self) -> int:
        """Total number of tool calls made."""
        return sum(self.by_tool.values())


class DiscoveryStats(BaseModel):
    """Statistics about tool discovery during a chat session.

    Only populated when tool discovery is enabled.
    """

    tools_discovered: int = Field(
        default=0,
        ge=0,
        description="Number of tools discovered (loaded) via search-tools",
    )
    search_calls: int = Field(
        default=0,
        ge=0,
        description="Number of search-tools invocations",
    )


class ChatStats(BaseModel):
    """Combined statistics from a chat session.

    Attributes:
        tokens: Token usage statistics across all LLM calls.
        tool_calls: Tool call counts by tool name and server.
        llm_calls: Number of LLM inference calls made.
        discovery: Tool discovery statistics. Only present (non-None)
            when tool discovery is enabled for the session.
    """

    tokens: TokenUsageStats = Field(default_factory=TokenUsageStats)
    tool_calls: ToolCallStats = Field(default_factory=ToolCallStats)
    llm_calls: int = Field(default=0, ge=0, description="Number of LLM calls made")
    discovery: DiscoveryStats | None = Field(
        default=None,
        description="Tool discovery statistics, present only when discovery is enabled",
    )
